language: elixir
sudo: false
script: mix test --include openssl
matrix:
  include:
  - elixir: '1.6.6'
    otp_release: '21.0'
  - elixir: '1.6.4'
    otp_release: '20.3'
  - elixir: '1.5.3'
    otp_release: '20.1'
